"use client"

import './globals.css'
import { Inter } from 'next/font/google'
import { useRouter } from "next/navigation"

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
    const { push } = useRouter()

    return (
        <html lang="en">
            <body className={inter.className}>
                <button className='absolute top-2 shadow-md z-10 left-2 bg-white border border-black rounded-sm px-2 py-1' onClick={() => push("/")}>HOME</button>
                {children}
            </body>
        </html>
    )
}
